/*
 * Netbeans 8.0 
 * JDK 1.7  
 */
package lcm.view;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import lcm.Plate;
import lcm.User;

/**
 *
 * @author casper
 */
public class FrameMain extends javax.swing.JFrame {

    /**
     * Creates new form FrameMain
     */
    private PanelIntroduction panelIntroduction;
    private PanelIdentity panelIdentity;
    private PanelDataUser panelDataUser;
    private PanelTest panelTest;
    private PanelResult panelResult;
    public static User USER;

    public FrameMain() {
        initComponents();
        new java.io.File("result").mkdirs();
        USER = new User();

        setTitle("APLIKASI TES BUTA WARNA | PENGACAKAN LCM & BBS");

        panelIntroduction = new PanelIntroduction(this);
        panelTest = new PanelTest(this);
        panelResult = new PanelResult(this);
        panelIdentity = new PanelIdentity(this);
        panelDataUser = new PanelDataUser(this);

        panelIntroduction.setOpaque(false);
        panelIdentity.setOpaque(false);
        panelDataUser.setOpaque(false);
        panelTest.setOpaque(false);
        panelResult.setOpaque(false);

        panelMain.add(panelIntroduction, "card1");
        panelMain.add(panelTest, "card2");
        panelMain.add(panelResult, "card3");

        jPanel1.add(panelIdentity, "card1");
        jPanel1.add(jpanelTest, "card2");
        jPanel1.add(panelDataUser, "card3");

//        setResizable(false);
        buttonTestResult.setEnabled(false);
        buttonIshiharaTest.setEnabled(false);
        
        
        showPanelIdentity();
    }

    public void showPanelIdentity() {
        setSize1();
        ((CardLayout) jPanel1.getLayout()).show(jPanel1, "card1");
    }

    public void showPanelTest() {
        setSize1();
        ((CardLayout) jPanel1.getLayout()).show(jPanel1, "card2");
    }

    public void showPanelUser() {
        setSize1();
        panelDataUser.setData();
        ((CardLayout) jPanel1.getLayout()).show(jPanel1, "card3");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iPanelBg1 = new lcm.component.IPanelBg();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpanelTest = new javax.swing.JPanel();
        panelMain = new lcm.component.IPanelGlass();
        jPanel2 = new javax.swing.JPanel();
        buttonIntroduction = new javax.swing.JButton();
        buttonIshiharaTest = new javax.swing.JButton();
        buttonTestResult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(543, 486));

        iPanelBg1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Batang", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TES BUTA WARNA");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tes Ishihara");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        iPanelBg1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.CardLayout());

        jpanelTest.setOpaque(false);

        panelMain.setLayout(new java.awt.CardLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setOpaque(false);

        buttonIntroduction.setText("Pengenalan");
        buttonIntroduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIntroductionActionPerformed(evt);
            }
        });
        jPanel2.add(buttonIntroduction);

        buttonIshiharaTest.setText("Tes Ishihara ");
        buttonIshiharaTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIshiharaTestActionPerformed(evt);
            }
        });
        jPanel2.add(buttonIshiharaTest);

        buttonTestResult.setText("Hasil Tes");
        buttonTestResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTestResultActionPerformed(evt);
            }
        });
        jPanel2.add(buttonTestResult);

        javax.swing.GroupLayout jpanelTestLayout = new javax.swing.GroupLayout(jpanelTest);
        jpanelTest.setLayout(jpanelTestLayout);
        jpanelTestLayout.setHorizontalGroup(
            jpanelTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelTestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpanelTestLayout.setVerticalGroup(
            jpanelTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelTestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jpanelTest, "card2");

        iPanelBg1.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(iPanelBg1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTestResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTestResultActionPerformed
        setSize2();
        showResult();
    }//GEN-LAST:event_buttonTestResultActionPerformed

    private void buttonIshiharaTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIshiharaTestActionPerformed
        setSize2();
        showCard("card2");
    }//GEN-LAST:event_buttonIshiharaTestActionPerformed

    private void buttonIntroductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIntroductionActionPerformed
        setSize1();
        showCard("card1");
    }//GEN-LAST:event_buttonIntroductionActionPerformed

    public void setSize1() {
        setSize(new Dimension(569, 530));
        setLocationRelativeTo(null);
    }
    
    public void setSize2() {
        setSize(new Dimension(1065, 605));
        setLocationRelativeTo(null);
    }
    
    public void showResult() {
        boolean bool1 = panelTest.getPanelIshiharaTest1().isFinish();
        boolean bool2 = panelTest.getPanelIshiharaTest2().isFinish();
        
        String time1 = panelTest.getPanelIshiharaTest1().getLabelTime().getText();
        String time2 = panelTest.getPanelIshiharaTest2().getLabelTime().getText();
        
        
        if(bool1 && bool2) {
            showCard("card3");
            panelResult.getPanelTestResult1().set(getListPlates1(), "LCM", time1);
            panelResult.getPanelTestResult2().set(getListPlates2(), "BBS", time2);
            buttonTestResult.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Silakan selesaikan soal tes terlebih dahulu ~ ", 
                    "APLIKASI TES BUTA WARNA | PENGACAKAN LCM & BBS", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void restartTest() {
        panelTest.restart();
        buttonIshiharaTest.setEnabled(false);
        buttonTestResult.setEnabled(false);
        setSize1();
    }

    public void startTest() {
        panelTest.start();
        buttonIshiharaTest.setEnabled(true);
        buttonTestResult.setEnabled(false);
        setSize2();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonIntroduction;
    private javax.swing.JButton buttonIshiharaTest;
    private javax.swing.JButton buttonTestResult;
    private lcm.component.IPanelBg iPanelBg1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpanelTest;
    private lcm.component.IPanelGlass panelMain;
    // End of variables declaration//GEN-END:variables

    public List<Plate> getListPlates1() {
        return panelTest.getPanelIshiharaTest1().getListPlates();
    }

    public List<Plate> getListPlates2() {
        return panelTest.getPanelIshiharaTest2().getListPlates();
    }
    
    public void showCard(String card) {
        ((CardLayout) panelMain.getLayout()).show(panelMain, card);
    }

    public JButton getButtonIshiharaTest() {
        return buttonIshiharaTest;
    }

}
